version: '3'
services:
  python-app:
    build: PythonBackend
    volumes:
      - "./PythonBackend:/app"
    ports:
      - "8008:8008"
    command:  
      -  /bin/bash
      -  -c
      -  |
          python3 main.py
          i=0
          while true
          do
            sleep 5
            ((i++))
          done

  react-app:
    build: AvatarUi
    volumes:
      - "./AvatarUi:/app"
    ports:
      - "5173:5173"
    command: 
    -  /bin/bash
    -  -c
    -  |
        npm run dev
        i=0
        while true
        do
          sleep 5
          ((i++))
        done

  node-backend:
    build: NodeBackend
    volumes:
      - "./NodeBackend:/app"

    ports:
      - "4000:4000"

    command: 

      -  /bin/bash
      -  -c
      -  |
          npm run start:dev
          i=0
          while true
          do
            sleep 5
            ((i++))
          done

    