# Use an official Node runtime as a parent image
FROM node:18


WORKDIR /app

COPY package*.json ./
RUN npm install
# Set the working directory to /app

# Install app dependencies
# RUN npm install

# Make port 3000 available to the world outside this container
# EXPOSE 5173

# Define the command to run your app
# CMD ["npm", "start"]
