version: '3.0'

services:
  postgres:
    image: postgres:latest  # Use an official PostgreSQL image from Docker Hub
    container_name: PD01-postgres
    # env_file: ../env  # Load environment variables from the .env file (ensure it exists)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: VirtualBot
    restart: always

    network_mode: "host"

    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  # Map data directory to host for persistence
